// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// Copyright 2026 Joshua Rich <joshua.rich@gmail.com>.

// SPDX-License-Identifier: 	AGPL-3.0-or-later

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sebasvil20/templicons/tabler"
import "github.com/immanent-tech/www-immanent-tech/web/templates/partials"

func Work() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-base-100\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = partials.Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"relative isolate mx-auto max-w-7xl px-6 lg:px-8 mt-36\"><div class=\"mx-auto max-w-2xl lg:mx-0\"><h2 class=\"text-4xl font-semibold tracking-tight text-pretty sm:text-5xl\">Our work</h2><p class=\"mt-6 text-lg/8\">We build small and wonderfully useful web things.</p></div><ul role=\"list\" class=\"mx-auto mt-20 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 sm:grid-cols-2 lg:mx-0 lg:max-w-none lg:grid-cols-3\"><li><a href=\"https://foragd.app\"><img src=\"/content/foragd-screenshot.webp\" alt=\"\" class=\"aspect-3/2 w-full rounded-2xl object-cover outline-1 -outline-offset-1 outline-neutral/5\"></a><h3 class=\"mt-6 text-lg/8 font-semibold tracking-tight\">Foragd</h3><p class=\"text-base/7\">A beautiful, web based, online feed reader.</p><ul role=\"list\" class=\"mt-6 flex gap-x-6\"><li><a href=\"https://foragd.app\" class=\"link link-hover\"><span class=\"sr-only\">Website</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = tabler.ExternalLink().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</a></li><li><a href=\"https://github.com/immanent-tech/foragd\" class=\"link link-hover\"><span class=\"sr-only\">Github</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = tabler.BrandGithub().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</a></li></ul></li><li><a href=\"https://github.com/immanent-tech/go-syndication\"><img src=\"https://opengraph.githubassets.com/0/immanent-tech/go-syndication\" alt=\"go-syndication GitHub Repository Thumbnail\" class=\"aspect-3/2 w-full rounded-2xl object-cover outline-1 -outline-offset-1 outline-neutral\"></a><h3 class=\"mt-6 text-lg/8 font-semibold tracking-tight\">go-syndication</h3><p class=\"text-base/7\">Syndication (RDF/RSS/Atom/JSONFeed) library for Go.</p><ul role=\"list\" class=\"mt-6 flex gap-x-6\"><li><a href=\"https://github.com/immanent-tech/go-syndication\" class=\"link link-hover\"><span class=\"sr-only\">Github</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = tabler.BrandGithub().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</a></li></ul></li><li><a href=\"https://github.com/immanent-tech/slog-elasticsearch\"><img src=\"https://opengraph.githubassets.com/0/immanent-tech/slog-elasticsearch\" alt=\"slog-elasticsearch GitHub Repository Thumbnail\" class=\"aspect-3/2 w-full rounded-2xl object-cover outline-1 -outline-offset-1 outline-neutral\"></a><h3 class=\"mt-6 text-lg/8 font-semibold tracking-tight\">slog-elasticsearch</h3><p class=\"text-base/7\">slog Elasticsearch handler.</p><ul role=\"list\" class=\"mt-6 flex gap-x-6\"><li><a href=\"https://github.com/immanent-tech/slog-elasticsearch\" class=\"link link-hover\"><span class=\"sr-only\">Github</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = tabler.BrandGithub().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</a></li></ul></li></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
